/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * footballCatalog.ts — full catalog of soccer competitions available on ESPN.
 * Generated from ESPN's league dropdown API (218 competitions).
 * Every entry uses a REAL ESPN slug, so no country/league shows up empty.
 */

export interface FootballLeagueEntry {
  code: string;
  slug: string;
  name: string;
  country: string;
}

export const FOOTBALL_CATALOG: FootballLeagueEntry[] = [
  { code: "FIFA_WORLD", slug: "fifa.world", name: "FIFA World Cup", country: "International" },
  { code: "FIFA_WWC", slug: "fifa.wwc", name: "FIFA Women's World Cup", country: "International" },
  { code: "UEFA_CHAMPIONS", slug: "uefa.champions", name: "UEFA Champions League", country: "Europe" },
  { code: "ENG_1", slug: "eng.1", name: "English Premier League", country: "England" },
  { code: "ENG_FA", slug: "eng.fa", name: "English FA Cup", country: "England" },
  { code: "ENG_LEAGUE_CUP", slug: "eng.league_cup", name: "English Carabao Cup", country: "England" },
  { code: "ESP_1", slug: "esp.1", name: "Spanish LALIGA", country: "Spain" },
  { code: "ENG_CHARITY", slug: "eng.charity", name: "English FA Community Shield", country: "England" },
  { code: "ESP_SUPER_CUP", slug: "esp.super_cup", name: "Spanish Supercopa", country: "Spain" },
  { code: "ESP_COPA_DEL_REY", slug: "esp.copa_del_rey", name: "Spanish Copa del Rey", country: "Spain" },
  { code: "USA_1", slug: "usa.1", name: "MLS", country: "USA" },
  { code: "CONCACAF_LEAGUES_CUP", slug: "concacaf.leagues.cup", name: "Leagues Cup", country: "North America" },
  { code: "CAMPEONES_CUP", slug: "campeones.cup", name: "Campeones Cup", country: "North America" },
  { code: "USA_NWSL", slug: "usa.nwsl", name: "NWSL", country: "USA" },
  { code: "USA_NWSL_CUP", slug: "usa.nwsl.cup", name: "NWSL Challenge Cup", country: "USA" },
  { code: "FIFA_SHEBELIEVES", slug: "fifa.shebelieves", name: "SheBelieves Cup", country: "International" },
  { code: "FIFA_W_CHAMPIONS_CUP", slug: "fifa.w.champions_cup", name: "FIFA Women's Champions Cup", country: "International" },
  { code: "UEFA_WCHAMPIONS", slug: "uefa.wchampions", name: "UEFA Women's Champions League", country: "Europe" },
  { code: "UEFA_EUROPA", slug: "uefa.europa", name: "UEFA Europa League", country: "Europe" },
  { code: "UEFA_EUROPA_CONF", slug: "uefa.europa.conf", name: "UEFA Conference League", country: "Europe" },
  { code: "FIFA_FRIENDLY", slug: "fifa.friendly", name: "International Friendly", country: "International" },
  { code: "MEX_1", slug: "mex.1", name: "Mexican Liga BBVA MX", country: "Mexico" },
  { code: "GER_1", slug: "ger.1", name: "German Bundesliga", country: "Germany" },
  { code: "GER_PLAYOFF_RELEGATION", slug: "ger.playoff.relegation", name: "German Bundesliga Promotion/Relegation Playoff", country: "Germany" },
  { code: "GER_DFB_POKAL", slug: "ger.dfb_pokal", name: "German Cup", country: "Germany" },
  { code: "ITA_1", slug: "ita.1", name: "Italian Serie A", country: "Italy" },
  { code: "ITA_COPPA_ITALIA", slug: "ita.coppa_italia", name: "Coppa Italia", country: "Italy" },
  { code: "FRA_1", slug: "fra.1", name: "French Ligue 1", country: "France" },
  { code: "FRA_SUPER_CUP", slug: "fra.super_cup", name: "French Trophee des Champions", country: "France" },
  { code: "ITA_SUPER_CUP", slug: "ita.super_cup", name: "Italian Supercoppa", country: "Italy" },
  { code: "GER_SUPER_CUP", slug: "ger.super_cup", name: "German Supercup", country: "Germany" },
  { code: "ENG_W_1", slug: "eng.w.1", name: "English Women's Super League", country: "England" },
  { code: "ENG_2", slug: "eng.2", name: "English League Championship", country: "England" },
  { code: "ENG_W_PROMOTION_RELEGATION", slug: "eng.w.promotion.relegation", name: "English Women's Super League Promotion/Relegation Playoff", country: "England" },
  { code: "NED_1", slug: "ned.1", name: "Dutch Eredivisie", country: "Netherlands" },
  { code: "POR_1", slug: "por.1", name: "Portuguese Primeira Liga", country: "Portugal" },
  { code: "FRA_COUPE_DE_FRANCE", slug: "fra.coupe_de_france", name: "Coupe de France", country: "France" },
  { code: "USA_OPEN", slug: "usa.open", name: "U.S. Open Cup", country: "USA" },
  { code: "KSA_1", slug: "ksa.1", name: "Saudi Pro League", country: "Saudi Arabia" },
  { code: "CLUB_FRIENDLY", slug: "club.friendly", name: "Club Friendly", country: "International" },
  { code: "CONMEBOL_LIBERTADORES", slug: "conmebol.libertadores", name: "CONMEBOL Libertadores", country: "South America" },
  { code: "CONCACAF_CHAMPIONS", slug: "concacaf.champions", name: "Concacaf Champions Cup", country: "North America" },
  { code: "FIFA_WORLDQ_UEFA", slug: "fifa.worldq.uefa", name: "FIFA World Cup Qualifying - UEFA", country: "International" },
  { code: "FIFA_WCQ_PLY", slug: "fifa.wcq.ply", name: "FIFA World Cup Qualifying - Playoff Tournament", country: "International" },
  { code: "FIFA_WORLDQ_CONCACAF", slug: "fifa.worldq.concacaf", name: "FIFA World Cup Qualifying - Concacaf", country: "International" },
  { code: "FIFA_WORLDQ_AFC", slug: "fifa.worldq.afc", name: "FIFA World Cup Qualifying - AFC", country: "International" },
  { code: "FIFA_WORLDQ_CAF", slug: "fifa.worldq.caf", name: "FIFA World Cup Qualifying - CAF", country: "International" },
  { code: "FIFA_WORLDQ_CONMEBOL", slug: "fifa.worldq.conmebol", name: "FIFA World Cup Qualifying - CONMEBOL", country: "International" },
  { code: "FIFA_WORLDQ_OFC", slug: "fifa.worldq.ofc", name: "FIFA World Cup Qualifying - OFC", country: "International" },
  { code: "UEFA_NATIONS", slug: "uefa.nations", name: "UEFA Nations League", country: "Europe" },
  { code: "FIFA_FRIENDLY_W", slug: "fifa.friendly.w", name: "Women's International Friendly", country: "International" },
  { code: "FIFA_WWORLDQ_UEFA", slug: "fifa.wworldq.uefa", name: "FIFA Women's World Cup Qualifying - UEFA", country: "International" },
  { code: "FIFA_WWCQ_PLY", slug: "fifa.wwcq.ply", name: "FIFA Women's World Cup Qualifying - Playoff Tournament", country: "International" },
  { code: "UEFA_W_NATIONS", slug: "uefa.w.nations", name: "UEFA Women's Nations League", country: "Europe" },
  { code: "USA_W_USL_1", slug: "usa.w.usl.1", name: "USL Super League", country: "USA" },
  { code: "UEFA_CHAMPIONS_QUAL", slug: "uefa.champions_qual", name: "UEFA Champions League Qualifying", country: "Europe" },
  { code: "UEFA_WCHAMPIONS_QUAL", slug: "uefa.wchampions_qual", name: "UEFA Women's Champions League Qualifying", country: "Europe" },
  { code: "ENG_W_FA", slug: "eng.w.fa", name: "English Women's FA Cup", country: "England" },
  { code: "ENG_W_LEAGUE_CUP", slug: "eng.w.league_cup", name: "English Women's League Cup", country: "England" },
  { code: "ESP_W_1", slug: "esp.w.1", name: "Spanish Liga F", country: "Spain" },
  { code: "ESP_COPA_DE_LA_REINA", slug: "esp.copa_de_la_reina", name: "Spanish Copa de la Reina", country: "Spain" },
  { code: "FRA_W_1", slug: "fra.w.1", name: "French Premi\u00e8re Ligue", country: "France" },
  { code: "NED_CUP", slug: "ned.cup", name: "Dutch KNVB Beker", country: "Netherlands" },
  { code: "SCO_1", slug: "sco.1", name: "Scottish Premiership", country: "Scotland" },
  { code: "SCO_TENNENTS", slug: "sco.tennents", name: "Scottish Cup", country: "Scotland" },
  { code: "SCO_CIS", slug: "sco.cis", name: "Scottish League Cup", country: "Scotland" },
  { code: "AUS_1", slug: "aus.1", name: "Australian A-League Men", country: "Australia" },
  { code: "AUS_W_1", slug: "aus.w.1", name: "Australian A-League Women", country: "Australia" },
  { code: "KSA_KINGS_CUP", slug: "ksa.kings.cup", name: "Saudi King's Cup", country: "Saudi Arabia" },
  { code: "POR_TACA_PORTUGAL", slug: "por.taca.portugal", name: "Taca de Portugal", country: "Portugal" },
  { code: "TUR_1", slug: "tur.1", name: "Turkish Super Lig", country: "Turkey" },
  { code: "CAF_NATIONS", slug: "caf.nations", name: "Africa Cup of Nations", country: "Africa" },
  { code: "AFC_CHAMPIONS", slug: "afc.champions", name: "AFC Champions League Elite", country: "Asia" },
  { code: "AFC_CUP", slug: "afc.cup", name: "AFC Champions League Two", country: "Asia" },
  { code: "FIFA_CWC", slug: "fifa.cwc", name: "FIFA Club World Cup", country: "International" },
  { code: "FIFA_OLYMPICS", slug: "fifa.olympics", name: "Men's Olympic Soccer Tournament", country: "International" },
  { code: "FIFA_W_OLYMPICS", slug: "fifa.w.olympics", name: "Women's Olympic Soccer Tournament", country: "International" },
  { code: "CONCACAF_GOLD", slug: "concacaf.gold", name: "Concacaf Gold Cup", country: "North America" },
  { code: "CONCACAF_GOLD_QUAL", slug: "concacaf.gold_qual", name: "Concacaf Gold Cup Qualifying", country: "North America" },
  { code: "CONCACAF_W_GOLD", slug: "concacaf.w.gold", name: "Concacaf W Gold Cup", country: "North America" },
  { code: "CONCACAF_NATIONS_LEAGUE", slug: "concacaf.nations.league", name: "Concacaf Nations League", country: "North America" },
  { code: "CONCACAF_CONFEDERATIONS_PLAYOFF", slug: "concacaf.confederations_playoff", name: "Concacaf Cup", country: "North America" },
  { code: "CONCACAF_W_CHAMPIONS_CUP", slug: "concacaf.w.champions_cup", name: "Concacaf W Champions Cup", country: "North America" },
  { code: "CONCACAF_WOMENS_CHAMPIONSHIP", slug: "concacaf.womens.championship", name: "Concacaf W Championship", country: "North America" },
  { code: "UEFA_EURO", slug: "uefa.euro", name: "UEFA European Championship", country: "Europe" },
  { code: "UEFA_EUROQ", slug: "uefa.euroq", name: "UEFA European Championship Qualifying", country: "Europe" },
  { code: "UEFA_WEURO", slug: "uefa.weuro", name: "UEFA Women's European Championship", country: "Europe" },
  { code: "UEFA_EURO_U21", slug: "uefa.euro_u21", name: "UEFA European Under-21 Championship", country: "Europe" },
  { code: "UEFA_SUPER_CUP", slug: "uefa.super_cup", name: "UEFA Super Cup", country: "Europe" },
  { code: "CONMEBOL_AMERICA", slug: "conmebol.america", name: "Copa Am\u00e9rica", country: "South America" },
  { code: "CONMEBOL_AMERICA_FEMENINA", slug: "conmebol.america.femenina", name: "Copa Am\u00e9rica Femenina", country: "South America" },
  { code: "USA_USL_1", slug: "usa.usl.1", name: "USL Championship", country: "USA" },
  { code: "USA_USL_L1", slug: "usa.usl.l1", name: "USL League One", country: "USA" },
  { code: "USA_USL_L1_CUP", slug: "usa.usl.l1.cup", name: "USL Cup", country: "USA" },
  { code: "MEX_2", slug: "mex.2", name: "Mexican Liga de Expansi\u00f3n MX", country: "Mexico" },
  { code: "GLOBAL_FINALISSIMA", slug: "global.finalissima", name: "CONMEBOL-UEFA Cup of Champions", country: "International" },
  { code: "GLOBAL_U20_INTERCONTINENTAL_CUP", slug: "global.u20.intercontinental_cup", name: "CONMEBOL-UEFA U20 Intercontinental Cup", country: "International" },
  { code: "GLOBAL_W_FINALISSIMA", slug: "global.w.finalissima", name: "CONMEBOL-UEFA Women's Cup of Champions", country: "International" },
  { code: "FIFA_WORLD_U20", slug: "fifa.world.u20", name: "FIFA Under-20 World Cup", country: "International" },
  { code: "AFC_ASIAN_CUP", slug: "afc.asian.cup", name: "AFC Asian Cup", country: "Asia" },
  { code: "AFC_W_ASIAN_CUP", slug: "afc.w.asian.cup", name: "AFC Women's Asian Cup", country: "Asia" },
  { code: "AFC_CUPQ", slug: "afc.cupq", name: "AFC Asian Cup Qualifiers", country: "Asia" },
  { code: "AFF_CHAMPIONSHIP", slug: "aff.championship", name: "ASEAN Championship", country: "Asia" },
  { code: "CAF_NATIONS_QUAL", slug: "caf.nations_qual", name: "Africa Cup of Nations Qualifying", country: "Africa" },
  { code: "CAF_W_NATIONS", slug: "caf.w.nations", name: "Women's Africa Cup of Nations", country: "Africa" },
  { code: "CAF_CHAMPIONSHIP", slug: "caf.championship", name: "African Nations Championship", country: "Africa" },
  { code: "CAN_W_NSL", slug: "can.w.nsl", name: "Northern Super League", country: "Canada" },
  { code: "UEFA_EUROPA_QUAL", slug: "uefa.europa_qual", name: "UEFA Europa League Qualifying", country: "Europe" },
  { code: "UEFA_EUROPA_CONF_QUAL", slug: "uefa.europa.conf_qual", name: "UEFA Conference League Qualifying", country: "Europe" },
  { code: "UEFA_W_EUROPA", slug: "uefa.w.europa", name: "UEFA Women's Europa Cup", country: "Europe" },
  { code: "FIFA_INTERCONTINENTAL_CUP", slug: "fifa.intercontinental_cup", name: "FIFA Intercontinental Cup", country: "International" },
  { code: "AFC_CHAMPIONS_QUAL", slug: "afc.champions_qual", name: "AFC Champions League Elite Qualifying", country: "Asia" },
  { code: "AFC_CUP_QUAL", slug: "afc.cup_qual", name: "AFC Champions League Two Qualifying", country: "Asia" },
  { code: "NONFIFA", slug: "nonfifa", name: "Non-FIFA Friendly", country: "International" },
  { code: "RUS_1", slug: "rus.1", name: "Russian Premier League", country: "Russia" },
  { code: "RUS_1_PROMOTION_RELEGATION", slug: "rus.1.promotion.relegation", name: "Russian Premier League Relegation/Promotion Playoffs", country: "Russia" },
  { code: "BEL_1", slug: "bel.1", name: "Belgian Pro League", country: "Belgium" },
  { code: "BEL_PROMOTION_RELEGATION", slug: "bel.promotion.relegation", name: "Belgian Pro League Promotion/Relegation Playoffs", country: "Belgium" },
  { code: "ESP_2", slug: "esp.2", name: "Spanish LALIGA 2", country: "Spain" },
  { code: "GER_2", slug: "ger.2", name: "German 2. Bundesliga", country: "Germany" },
  { code: "ITA_2", slug: "ita.2", name: "Italian Serie B", country: "Italy" },
  { code: "FRA_1_PROMOTION_RELEGATION", slug: "fra.1.promotion.relegation", name: "French Ligue 1 Promotion/Relegation Playoffs", country: "France" },
  { code: "FRA_2", slug: "fra.2", name: "French Ligue 2", country: "France" },
  { code: "POR_1_PROMOTION_RELEGATION", slug: "por.1.promotion.relegation", name: "Portuguese Primeira Liga Promotion/Relegation Playoffs", country: "Portugal" },
  { code: "AUT_1", slug: "aut.1", name: "Austrian Bundesliga", country: "Austria" },
  { code: "GRE_1", slug: "gre.1", name: "Greek Super League", country: "Greece" },
  { code: "CHN_1", slug: "chn.1", name: "Chinese Super League", country: "China" },
  { code: "GLOBAL_CLUB_CHALLENGE", slug: "global.club_challenge", name: "CONMEBOL-UEFA Club Challenge", country: "International" },
  { code: "NED_SUPERCUP", slug: "ned.supercup", name: "Dutch Johan Cruyff Shield", country: "Netherlands" },
  { code: "GLOBAL_PINATAR_CUP", slug: "global.pinatar_cup", name: "Pinatar Cup", country: "International" },
  { code: "FRIENDLY_EMIRATES_CUP", slug: "friendly.emirates_cup", name: "Emirates Cup", country: "International" },
  { code: "ESP_JOAN_GAMPER", slug: "esp.joan_gamper", name: "Trofeo Joan Gamper", country: "Spain" },
  { code: "JPN_WORLD_CHALLENGE", slug: "jpn.world_challenge", name: "Japanese J.League World Challenge", country: "Japan" },
  { code: "GLOBAL_ARNOLD_CLARK_CUP", slug: "global.arnold.clark_cup", name: "Arnold Clark Cup", country: "International" },
  { code: "FIFA_CONMEBOL_OLYMPICSQ", slug: "fifa.conmebol.olympicsq", name: "CONMEBOL Pre-Olympic Tournament", country: "International" },
  { code: "FIFA_CONCACAF_OLYMPICSQ", slug: "fifa.concacaf.olympicsq", name: "Men's Olympic Qualifying Playoff", country: "International" },
  { code: "FIFA_W_CONCACAF_OLYMPICSQ", slug: "fifa.w.concacaf.olympicsq", name: "Concacaf Women's Olympic Qualifying", country: "International" },
  { code: "FIFA_WORLD_U17", slug: "fifa.world.u17", name: "FIFA Under-17 World Cup", country: "International" },
  { code: "FIFA_WWORLD_U17", slug: "fifa.wworld.u17", name: "FIFA Under-17 Women's World Cup", country: "International" },
  { code: "UEFA_EURO_U21_QUAL", slug: "uefa.euro_u21_qual", name: "UEFA European Under-21 Championship Qualifying", country: "Europe" },
  { code: "UEFA_EURO_U19", slug: "uefa.euro.u19", name: "UEFA European Under-19 Championship", country: "Europe" },
  { code: "FIFA_FRIENDLY_U21", slug: "fifa.friendly_u21", name: "Under-21 International Friendly", country: "International" },
  { code: "GER_2_PROMOTION_RELEGATION", slug: "ger.2.promotion.relegation", name: "German Bundesliga 2. Promotion/Relegation Playoffs", country: "Germany" },
  { code: "ENG_TROPHY", slug: "eng.trophy", name: "English EFL Trophy", country: "England" },
  { code: "ENG_3", slug: "eng.3", name: "English League One", country: "England" },
  { code: "ENG_4", slug: "eng.4", name: "English League Two", country: "England" },
  { code: "ENG_5", slug: "eng.5", name: "English National League", country: "England" },
  { code: "ENG_FA_QUAL", slug: "eng.fa_qual", name: "English FA Cup Qualifying", country: "England" },
  { code: "SCO_1_PROMOTION_RELEGATION", slug: "sco.1.promotion.relegation", name: "Scottish Premiership Promotion/Relegation Playoffs", country: "Scotland" },
  { code: "SCO_2", slug: "sco.2", name: "Scottish Championship", country: "Scotland" },
  { code: "SCO_2_PROMOTION_RELEGATION", slug: "sco.2.promotion.relegation", name: "Scottish Championship Promotion/Relegation Playoffs", country: "Scotland" },
  { code: "SCO_CHALLENGE", slug: "sco.challenge", name: "Scottish League Challenge Cup", country: "Scotland" },
  { code: "SCO_TENNENTS_QUAL", slug: "sco.tennents_qual", name: "Scottish Cup Qualifying", country: "Scotland" },
  { code: "NED_PLAYOFF_RELEGATION", slug: "ned.playoff.relegation", name: "Dutch Eredivisie Promotion/Relegation Playoffs", country: "Netherlands" },
  { code: "NED_2", slug: "ned.2", name: "Dutch Keuken Kampioen Divisie", country: "Netherlands" },
  { code: "NED_3_PROMOTION_RELEGATION", slug: "ned.3.promotion.relegation", name: "Dutch Tweede Divisie Promotion/Relegation Playoffs", country: "Netherlands" },
  { code: "NED_W_KNVB_CUP", slug: "ned.w.knvb_cup", name: "Dutch KNVB Beker Vrouwen", country: "Netherlands" },
  { code: "NED_W_1", slug: "ned.w.1", name: "Dutch Vrouwen Eredivisie", country: "Netherlands" },
  { code: "SWE_1", slug: "swe.1", name: "Swedish Allsvenskan", country: "Sweden" },
  { code: "SWE_1_PROMOTION_RELEGATION", slug: "swe.1.promotion.relegation", name: "Swedish Allsvenskan Promotion/Relegation Playoffs", country: "Sweden" },
  { code: "DEN_1", slug: "den.1", name: "Danish Superliga", country: "Denmark" },
  { code: "NOR_1_PROMOTION_RELEGATION", slug: "nor.1.promotion.relegation", name: "Norwegian Eliteserien Promotion/Relegation Playoffs", country: "Norway" },
  { code: "NOR_1", slug: "nor.1", name: "Norwegian Eliteserien", country: "Norway" },
  { code: "CONMEBOL_SUDAMERICANA", slug: "conmebol.sudamericana", name: "CONMEBOL Sudamericana", country: "South America" },
  { code: "CONMEBOL_RECOPA", slug: "conmebol.recopa", name: "CONMEBOL Recopa", country: "South America" },
  { code: "ARG_1", slug: "arg.1", name: "Argentine Liga Profesional de F\u00fatbol", country: "Argentina" },
  { code: "ARG_COPA", slug: "arg.copa", name: "Copa Argentina", country: "Argentina" },
  { code: "ARG_COPA_DE_LA_SUPERLIGA", slug: "arg.copa_de_la_superliga", name: "Argentine Copa de la Superliga", country: "Argentina" },
  { code: "ARG_TROFEO_DE_LA_CAMPEONES", slug: "arg.trofeo_de_la_campeones", name: "Argentine Trofeo de Campeones", country: "Argentina" },
  { code: "ARG_2", slug: "arg.2", name: "Argentine Nacional B", country: "Argentina" },
  { code: "ARG_SUPERCOPA", slug: "arg.supercopa", name: "Argentine Supercopa", country: "Argentina" },
  { code: "ARG_SUPERCOPA_INTERNACIONAL", slug: "arg.supercopa.internacional", name: "Argentine Supercopa Internacional", country: "Argentina" },
  { code: "ARG_3", slug: "arg.3", name: "Argentine Primera B", country: "Argentina" },
  { code: "BRA_SUPERCOPA_DO_BRAZIL", slug: "bra.supercopa_do_brazil", name: "Brazilian Supercopa Rei", country: "Brazil" },
  { code: "BRA_1", slug: "bra.1", name: "Brazilian Serie A", country: "Brazil" },
  { code: "BRA_2", slug: "bra.2", name: "Brazilian Serie B", country: "Brazil" },
  { code: "BRA_COPA_DO_BRAZIL", slug: "bra.copa_do_brazil", name: "Copa do Brasil", country: "Brazil" },
  { code: "BRA_CAMP_CARIOCA", slug: "bra.camp.carioca", name: "Brazilian Campeonato Carioca", country: "Brazil" },
  { code: "BRA_CAMP_PAULISTA", slug: "bra.camp.paulista", name: "Brazilian Campeonato Paulista", country: "Brazil" },
  { code: "BRA_CAMP_GAUCHO", slug: "bra.camp.gaucho", name: "Brazilian Campeonato Gaucho", country: "Brazil" },
  { code: "BRA_CAMP_MINEIRO", slug: "bra.camp.mineiro", name: "Brazilian Campeonato Mineiro", country: "Brazil" },
  { code: "CHI_SUPER_CUP", slug: "chi.super_cup", name: "Chilean Supercopa", country: "Chile" },
  { code: "CHI_1", slug: "chi.1", name: "Chilean Primera Divisi\u00f3n", country: "Chile" },
  { code: "CHI_1_PROMOTION_RELEGATION", slug: "chi.1.promotion.relegation", name: "Chilean Primera Divisi\u00f3n Promotion/Relegation Playoffs", country: "Chile" },
  { code: "CHI_COPA_CHI", slug: "chi.copa_chi", name: "Copa Chile", country: "Chile" },
  { code: "URU_1", slug: "uru.1", name: "Liga AUF Uruguaya", country: "Uruguay" },
  { code: "URU_2", slug: "uru.2", name: "Segunda Divisi\u00f3n de Uruguay", country: "Uruguay" },
  { code: "COL_SUPERLIGA", slug: "col.superliga", name: "Colombian Superliga", country: "Colombia" },
  { code: "COL_1", slug: "col.1", name: "Colombian Primera A", country: "Colombia" },
  { code: "COL_COPA", slug: "col.copa", name: "Copa Colombia", country: "Colombia" },
  { code: "PER_1", slug: "per.1", name: "Peruvian Liga 1", country: "Peru" },
  { code: "PAR_1", slug: "par.1", name: "Paraguayan Primera Divisi\u00f3n", country: "Paraguay" },
  { code: "PAR_1_SUPERCOPA", slug: "par.1.supercopa", name: "Paraguayan Supercopa", country: "Paraguay" },
  { code: "ECU_1", slug: "ecu.1", name: "LigaPro Ecuador", country: "Ecuador" },
  { code: "VEN_1", slug: "ven.1", name: "Venezuelan Primera Divisi\u00f3n", country: "Venezuela" },
  { code: "BOL_PLY_REL", slug: "bol.ply.rel", name: "Bolivian Liga Profesional Promotion/Relegation Playoffs", country: "Bolivia" },
  { code: "BOL_COPA", slug: "bol.copa", name: "Copa Bolivia", country: "Bolivia" },
  { code: "BOL_1", slug: "bol.1", name: "Bolivian Liga Profesional", country: "Bolivia" },
  { code: "JPN_1", slug: "jpn.1", name: "Japanese J.League", country: "Japan" },
  { code: "MEX_CAMPEON", slug: "mex.campeon", name: "Mexican Campeon de Campeones", country: "Mexico" },
  { code: "CONCACAF_CENTRAL_AMERICAN_CUP", slug: "concacaf.central.american.cup", name: "Concacaf Central American Cup", country: "North America" },
  { code: "CONCACAF_CHAMPIONS_CUP", slug: "concacaf.champions_cup", name: "CONCACAF Champions Cup", country: "North America" },
  { code: "CONCACAF_U23", slug: "concacaf.u23", name: "CONCACAF U23 Tournament", country: "North America" },
  { code: "HON_1", slug: "hon.1", name: "Honduran Liga Nacional", country: "Honduras" },
  { code: "CRC_1", slug: "crc.1", name: "Costa Rican Primera Division", country: "Costa Rica" },
  { code: "GUA_1", slug: "gua.1", name: "Guatemalan Liga Nacional", country: "Guatemala" },
  { code: "SLV_1", slug: "slv.1", name: "Salvadoran Primera Division", country: "El Salvador" },
  { code: "FIFA_INTERCONTINENTAL_CUP", slug: "fifa.intercontinental.cup", name: "Intercontinental Cup (India)", country: "International" },
  { code: "AFC_SAFF_CHAMPIONSHIP", slug: "afc.saff.championship", name: "SAFF Championship", country: "Asia" },
  { code: "CHN_1_PROMOTION_RELEGATION", slug: "chn.1.promotion.relegation", name: "Chinese Super League Promotion/Relegation Playoffs", country: "China" },
  { code: "IND_1", slug: "ind.1", name: "Indian Super League", country: "India" },
  { code: "GLOBAL_GULF_CUP", slug: "global.gulf_cup", name: "Arabian Gulf Cup", country: "International" },
  { code: "CAF_COSAFA", slug: "caf.cosafa", name: "COSAFA Cup", country: "Africa" },
  { code: "CAF_CHAMPIONS", slug: "caf.champions", name: "CAF Champions League", country: "Africa" },
  { code: "CAF_CONFED", slug: "caf.confed", name: "CAF Confederation Cup", country: "Africa" },
  { code: "RSA_1", slug: "rsa.1", name: "South African Premiership", country: "South Africa" },
  { code: "USA_NCAA_M_1", slug: "usa.ncaa.m.1", name: "NCAA Men's Soccer", country: "USA" },
  { code: "USA_NCAA_W_1", slug: "usa.ncaa.w.1", name: "NCAA Women's Soccer", country: "USA" },
];

/** code -> ESPN slug map for every catalog entry. */
export const CATALOG_LEAGUE_SLUGS: Record<string, string> = Object.fromEntries(
  FOOTBALL_CATALOG.map((l) => [l.code, l.slug])
);

/** country -> leagues, sorted alphabetically by country. */
export const FOOTBALL_BY_COUNTRY: Record<string, FootballLeagueEntry[]> = FOOTBALL_CATALOG.reduce(
  (acc, l) => {
    (acc[l.country] ||= []).push(l);
    return acc;
  },
  {} as Record<string, FootballLeagueEntry[]>
);

export function getFootballLeagueByCode(code: string): FootballLeagueEntry | undefined {
  return FOOTBALL_CATALOG.find((l) => l.code === code.toUpperCase());
}
