const competitions = [
  { code: "NBA", slug: "nba", name: "National Basketball Association", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "WNBA", slug: "wnba", name: "Women's NBA", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/wnba.png" },
  { code: "NCAAM", slug: "mens-college-basketball", name: "NCAA Men's Basketball", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/mens-college-basketball.png" },
  { code: "NCAAW", slug: "womens-college-basketball", name: "NCAA Women's Basketball", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/womens-college-basketball.png" },
  { code: "NBAG", slug: "nba-development", name: "NBA G League", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba-g-league.png" },
  { code: "NBASLV", slug: "nba-summer-las-vegas", name: "NBA Summer League (Las Vegas)", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "NBASC", slug: "nba-summer-california", name: "NBA California Classic", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "NBASS", slug: "nba-summer-sacramento", name: "NBA Sacramento Summer League", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "NBAUT", slug: "nba-summer-utah", name: "NBA Salt Lake City Summer League", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "NBAGS", slug: "nba-summer-golden-state", name: "NBA Golden State Summer League", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "NBAOR", slug: "nba-summer-orlando", name: "NBA Orlando Summer League", country: "USA", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
  { code: "ACB", slug: "acb", name: "Liga ACB / Copa del Rey", country: "Spain", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/acb.png" },
  { code: "LBA", slug: "lba", name: "Lega Basket Serie A", country: "Italy", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/lba.png" },
  { code: "NBL", slug: "nbl", name: "National Basketball League", country: "Australia", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nbl.png" },
  { code: "NBB", slug: "nbb", name: "Novo Basquete Brasil", country: "Brazil", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/nbb.png" },
  { code: "EURO", slug: "euroleague", name: "EuroLeague", country: "Europe", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/euroleague.png" },
  { code: "FIBA", slug: "fiba", name: "FIBA Basketball World Cup", country: "International", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/fiba.png" },
  { code: "FIBAAM", slug: "fiba-americas", name: "FIBA AmeriCup", country: "International", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/fiba-americas.png" },
  { code: "OLYM", slug: "mens-olympics-basketball", name: "Olympics Men's Basketball", country: "International", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/olympics.png" },
  { code: "OLYW", slug: "womens-olympics-basketball", name: "Olympics Women's Basketball", country: "International", emblemUrl: "https://a.espncdn.com/i/teamlogos/leagues/500/olympics.png" },
];
export const onRequest = async () => Response.json({ ok: true, provider: "espn", competitions });
