/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MatchTip, Tipster } from "./types";

export const SPORTS_CATEGORIES = [
  { id: "All", name: "All", icon: "Zap" },
  { id: "Football", name: "Football", icon: "Activity" },
  { id: "Games", name: "Games", icon: "Gamepad2" },
  { id: "Basketball", name: "Basketball", icon: "Trophy" },
  { id: "Tennis", name: "Tennis", icon: "Target" },
  { id: "Volleyball", name: "Volleyball", icon: "CircleDot" },
  { id: "Golf", name: "Golf", icon: "Compass" },
  { id: "Boxing", name: "Boxing", icon: "ShieldAlert" },
  { id: "Rugby", name: "Rugby", icon: "Award" },
];

export const LEAGUE_FILTERS = [{ id: "All", name: "All" }];

export const INITIAL_MATCH_TIPS: MatchTip[] = [
  {
    id: "tip-valencia-betis",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Man",
    time: "Leo, 20:30 EAT",
    status: "LIVE",
    liveMinutes: "74'",
    liveScore: "2 - 1",
    confidence: 86,
    homeTeam: {
      name: "Valencia",
      bgGlow: "rgba(249, 115, 22, 0.4)", // Orange
    },
    awayTeam: {
      name: "Real Betis",
      bgGlow: "rgba(16, 185, 129, 0.4)", // Green
    },
    odds: {
      home: 2.3,
      draw: 3.1,
      away: 2.95,
    },
    payoutBadge: "FBU 1,500k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TakeTalon Pro",
      avatarLetter: "T",
      badge: "LIVE",
      isOfficial: true,
    },
    predictionTip: "Valencia kushinda au Sare (1X) & Magoli zaidi ya 1.5",
    analysisText:
      "Pambano hili la LaLiga lina mvuto mkubwa sana. Valencia wako mbele kwa 2-1 Mestalla kwa mashambulizi ya kasi kupitia mabawa, huku Real Betis wakisaka bao la kusawazisha katika dakika hizi za mwisho.",
  },
  {
    id: "tip-1",
    sport: "Football",
    category: "Tanzania",
    league: "Ligi Kuu Bara",
    gender: "Man",
    time: "Leo, 19:00 EAT",
    status: "LIVE",
    liveMinutes: "68'",
    liveScore: "1 - 1",
    confidence: 78,
    homeTeam: {
      name: "Simba SC",
      bgGlow: "rgba(239, 68, 68, 0.4)", // Red
    },
    awayTeam: {
      name: "Yanga SC",
      bgGlow: "rgba(234, 179, 8, 0.4)", // Yellow
    },
    odds: {
      home: 2.15,
      draw: 3.2,
      away: 2.8,
    },
    payoutBadge: "FBU 1,000k+",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TalonTake J.",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Simba SC kushinda au Sare (1X) & Magoli chini ya 2.5",
    analysisText:
      "Pambano hili la dabi ya Kariakoo lina ushindani mkubwa sana. Simba SC wapo nyumbani wakiwa na fomu nzuri lakini Yanga wana safu imara ya ulinzi. Kutokana na presha kubwa ya mashabiki, mchezo utakuwa wa tahadhari na magoli yatakuwa machache.",
  },
  {
    id: "tip-2",
    sport: "Football",
    category: "UK",
    league: "Premier League",
    gender: "Man",
    time: "Jumapili, 20:45 EAT",
    status: "UPCOMING",
    confidence: 89,
    homeTeam: {
      name: "Liverpool",
      bgGlow: "rgba(220, 38, 38, 0.4)", // Red
    },
    awayTeam: {
      name: "Man City",
      bgGlow: "rgba(14, 165, 233, 0.4)", // Sky blue
    },
    odds: {
      home: 1.75,
      draw: 3.6,
      away: 4.2,
    },
    payoutBadge: "FBU 800k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TakeTalon Pro",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Liverpool kupata ushindi (Home Win) au magoli zaidi ya 1.5",
    analysisText:
      "Anfield itakuwa na nguvu ya ziada. Liverpool wamekuwa na muundo thabiti msimu huu, huku Man City wakiwa na mapungufu kadhaa kwenye safu yao ya kiungo baada ya majeraha. Odds ya 1.75 ina thamani kubwa sana.",
  },
  {
    id: "tip-3",
    sport: "Basketball",
    category: "USA",
    league: "NBA",
    gender: "Man",
    time: "20 Juni, 03:00 EAT",
    status: "ENDED",
    confidence: 89,
    homeTeam: {
      name: "Milwaukee Bucks",
      bgGlow: "rgba(21, 128, 61, 0.4)", // Green
    },
    awayTeam: {
      name: "Miami Heat",
      bgGlow: "rgba(239, 68, 68, 0.4)", // Red/Orange
    },
    odds: {
      home: 1.65,
      draw: 14.0,
      away: 2.25,
    },
    payoutBadge: "FBU 1000k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TakeTalon J.",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Milwaukee Bucks Kushinda (FT)",
    analysisText:
      "Bucks walionyesha kiwango thabiti nyumbani kwa kuzuia mashambulizi ya karibu ya Miami Heat. Ushindi wao ulikuwa wa wazi kabisa.",
  },
  {
    id: "tip-4",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Man",
    time: "Jumatano, 22:00 EAT",
    status: "UPCOMING",
    confidence: 71,
    homeTeam: {
      name: "Barcelona",
      bgGlow: "rgba(30, 58, 138, 0.4)", // Deep Blue
    },
    awayTeam: {
      name: "Man City",
      bgGlow: "rgba(14, 165, 233, 0.4)", // Sky Blue
    },
    odds: {
      home: 2.4,
      draw: 3.5,
      away: 2.1,
    },
    payoutBadge: "FBU 350k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "BetMaster TZ",
      avatarLetter: "B",
      badge: "LIVE",
      isOfficial: false,
    },
    predictionTip: "Ubashiri wa Siri: Magoli ya Kipekee & Mshindi",
    analysisText:
      "Uchambuzi huu umefungwa kwa wanachama wa PRO pekee. Barcelona ina mbinu mpya ya kuzuia huku Man City wakiwa hatari kwenye mashambulizi ya kushtukiza. Doti hii ya dhahabu inahusisha double chance maalum na idadi ya kona.",
  },
  {
    id: "tip-5",
    sport: "Football",
    category: "International",
    league: "International Cup",
    gender: "Man",
    time: "Kesho, 16:00 EAT",
    status: "UPCOMING",
    confidence: 84,
    homeTeam: {
      name: "Azam FC",
      bgGlow: "rgba(59, 130, 246, 0.4)", // Blue
    },
    awayTeam: {
      name: "Singida FG",
      bgGlow: "rgba(16, 185, 129, 0.4)", // Green
    },
    odds: {
      home: 1.82,
      draw: 3.4,
      away: 3.95,
    },
    payoutBadge: "FBU 500k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Elite Tips",
      avatarLetter: "E",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Doti ya Siri ya Ligi Kuu Bara",
    analysisText:
      "Uchambuzi wa siri wa kiufundi kuhusu Azam FC nyumbani kwao Chamazi Complex dhidi ya Singida FG.",
  },
  {
    id: "tip-6",
    sport: "Tennis",
    category: "UK",
    league: "Wimbledon",
    gender: "Man",
    time: "Ijumaa, 15:00 EAT",
    status: "UPCOMING",
    confidence: 91,
    homeTeam: {
      name: "Alcaraz C.",
      bgGlow: "rgba(168, 85, 247, 0.4)", // Purple
    },
    awayTeam: {
      name: "Djokovic N.",
      bgGlow: "rgba(34, 197, 94, 0.4)", // Green
    },
    odds: {
      home: 1.95,
      draw: 1.0, // No draw in tennis, but keeping visual structure
      away: 1.8,
    },
    payoutBadge: "FBU 1,200k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TenisMaster",
      avatarLetter: "M",
      badge: "ELITE",
      isOfficial: false,
    },
    predictionTip: "Alcaraz C. Kushinda Seti ya Kwanza",
    analysisText:
      "Alcaraz ameonyesha kasi na nguvu ya ziada kwenye viwanja vya nyasi. Kuanza kwake kwa kasi kutamfanya achukue seti ya kwanza mapema dhidi ya mkongwe Djokovic.",
  },
  {
    id: "tip-7",
    sport: "Volleyball",
    category: "Italy",
    league: "Serie A1",
    gender: "Man",
    time: "Kesho, 18:00 EAT",
    status: "UPCOMING",
    confidence: 85,
    homeTeam: {
      name: "Lube Civitanova",
      bgGlow: "rgba(220, 38, 38, 0.3)",
    },
    awayTeam: {
      name: "Sir Safety Perugia",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 1.85,
      draw: 1.0,
      away: 1.9,
    },
    payoutBadge: "FBU 400k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "VolleyGuru",
      avatarLetter: "V",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Sir Safety Perugia Kushinda",
    analysisText:
      "Perugia wapo kwenye fomu nzuri sana msimu huu na wamekuwa wakiongoza ligi. Mechi hii itakuwa ya upinzani lakini watashinda.",
  },
  {
    id: "tip-8",
    sport: "Golf",
    category: "UK",
    league: "The Open Championship",
    gender: "Man",
    time: "Leo, 14:00 EAT",
    status: "LIVE",
    liveMinutes: "Round 2",
    confidence: 82,
    homeTeam: {
      name: "Rory McIlroy",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    awayTeam: {
      name: "Scottie Scheffler",
      bgGlow: "rgba(139, 92, 246, 0.3)",
    },
    odds: {
      home: 2.1,
      draw: 10.0,
      away: 1.7,
    },
    payoutBadge: "FBU 900k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "GolfPick",
      avatarLetter: "G",
      badge: "GOLD",
      isOfficial: false,
    },
    predictionTip: "Scottie Scheffler Kuongoza Round 2",
    analysisText:
      "Scheffler ana kiwango kikubwa sana cha 'putting' kwa sasa na uwanja huu wa nyasi wa Uingereza unamfaa sana.",
  },
  {
    id: "tip-9",
    sport: "Boxing",
    category: "UK",
    league: "Matchroom Boxing",
    gender: "Man",
    time: "Kesho, 23:30 EAT",
    status: "UPCOMING",
    confidence: 93,
    homeTeam: {
      name: "Tyson Fury",
      bgGlow: "rgba(245, 158, 11, 0.3)",
    },
    awayTeam: {
      name: "Oleksandr Usyk",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    odds: {
      home: 1.91,
      draw: 15.0,
      away: 1.91,
    },
    payoutBadge: "FBU 2,500k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "RingMaster",
      avatarLetter: "R",
      badge: "VIP",
      isOfficial: true,
    },
    predictionTip: "Pambano Kwenda Maamuzi ya Majaji (Over 10.5 Rounds)",
    analysisText:
      "Mabondia wote wawili wana ulinzi mzuri na mbinu za hali ya juu za kukwepa ngumi. Hakuna uwezekano mkubwa av KO ya mapema.",
  },
  {
    id: "tip-10",
    sport: "Rugby",
    category: "France",
    league: "Top 14",
    gender: "Man",
    time: "Jumapili, 17:00 EAT",
    status: "UPCOMING",
    confidence: 88,
    homeTeam: {
      name: "Toulouse",
      bgGlow: "rgba(239, 68, 68, 0.3)",
    },
    awayTeam: {
      name: "La Rochelle",
      bgGlow: "rgba(234, 179, 8, 0.3)",
    },
    odds: {
      home: 1.45,
      draw: 22.0,
      away: 2.85,
    },
    payoutBadge: "FBU 650k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "RugbyPro",
      avatarLetter: "R",
      badge: "TOP",
      isOfficial: false,
    },
    predictionTip: "Toulouse Kushinda kwa Handikap (-5.5)",
    analysisText:
      "Toulouse wana kikosi kipana na wameshinda mechi zote tano za nyumbani msimu huu kwa tofauti ya alama zaidi ya 10.",
  },
  {
    id: "tip-11",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Woman",
    time: "Kesho, 18:30 EAT",
    status: "UPCOMING",
    confidence: 94,
    homeTeam: {
      name: "Barcelona Femeni",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    awayTeam: {
      name: "Real Madrid Femenino",
      bgGlow: "rgba(255, 255, 255, 0.15)",
    },
    odds: {
      home: 1.18,
      draw: 6.5,
      away: 12.0,
    },
    payoutBadge: "FBU 1,500k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Barcelona Femeni Kushinda (FT)",
    analysisText:
      "Barcelona Femeni wako kwenye kiwango cha kimbunga kikubwa msimu huu, wakiwa wameshinda mechi zote za nyumbani na kufunga mabao mengi.",
  },
  {
    id: "tip-12",
    sport: "Football",
    category: "UK",
    league: "Premier League",
    gender: "Woman",
    time: "Jumapili, 15:00 EAT",
    status: "UPCOMING",
    confidence: 86,
    homeTeam: {
      name: "Chelsea FC Women",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "Arsenal WFC",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    odds: {
      home: 1.95,
      draw: 3.4,
      away: 3.1,
    },
    payoutBadge: "FBU 750k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LionessBets",
      avatarLetter: "L",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Magoli zaidi ya 2.5 (Over 2.5 Goals)",
    analysisText:
      "Mechi hizi za dabi ya London kwa wanawake huwa na mabao mengi sana kutokana na ushambuliaji mkali wa timu zote mbili.",
  },
  {
    id: "tip-13",
    sport: "Basketball",
    category: "USA",
    league: "NBA",
    gender: "Woman",
    time: "Leo, 02:00 EAT",
    status: "LIVE",
    liveMinutes: "Q3 04:12",
    confidence: 88,
    homeTeam: {
      name: "New York Liberty",
      bgGlow: "rgba(56, 189, 248, 0.4)",
    },
    awayTeam: {
      name: "Las Vegas Aces",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    odds: {
      home: 1.7,
      draw: 11.0,
      away: 2.15,
    },
    payoutBadge: "FBU 1,100k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "WNBAPredict",
      avatarLetter: "W",
      badge: "VIP",
      isOfficial: false,
    },
    predictionTip: "New York Liberty Kushinda kwa Handikap (-3.5)",
    analysisText:
      "Liberty wapo imara sana wakiwa nyumbani Barclays Center na wanalipiza kisasi cha msimu uliopita dhidi ya Aces.",
  },
  {
    id: "tip-14",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Man",
    time: "Leo, 22:00 EAT",
    status: "LIVE",
    liveMinutes: "12'",
    confidence: 88,
    homeTeam: {
      name: "Real Madrid",
      bgGlow: "rgba(255, 255, 255, 0.25)",
    },
    awayTeam: {
      name: "Atletico Madrid",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    odds: {
      home: 1.8,
      draw: 3.5,
      away: 4.5,
    },
    payoutBadge: "FBU 1,200k+",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Mtabiri Mkuu",
      avatarLetter: "M",
      isOfficial: false,
    },
    predictionTip: "Real Madrid Kushinda (FT)",
    analysisText:
      "Madrid Derby inasisimua sana kwenye uwanja wa Santiago Bernabeu. Real Madrid wapo kwenye kiwango bora wakiwa nyumbani na uwezekano wa kushinda leo ni mkubwa.",
  },
  {
    id: "tip-15",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Woman",
    time: "Leo, 16:00 EAT",
    status: "UPCOMING",
    confidence: 83,
    homeTeam: {
      name: "Atletico Madrid Femenino",
      bgGlow: "rgba(239, 68, 68, 0.3)",
    },
    awayTeam: {
      name: "Levante Femenino",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 2.1,
      draw: 3.3,
      away: 3.2,
    },
    payoutBadge: "FBU 500k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Magoli zaidi ya 1.5 (Over 1.5 Goals)",
    analysisText:
      "Mechi hii itakuwa ya kushambuliana kwa pande zote mbili. Takwimu zinaonyesha mechi zao zote zilizopita zilikuwa na mabao zaidi ya mawili.",
  },
  {
    id: "tip-16",
    sport: "Football",
    category: "Tanzania",
    league: "Ligi Kuu Bara",
    gender: "Man",
    time: "Kesho, 19:00 EAT",
    status: "UPCOMING",
    confidence: 90,
    homeTeam: {
      name: "Azam FC",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "Simba SC",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    odds: {
      home: 2.45,
      draw: 3.1,
      away: 2.75,
    },
    payoutBadge: "FBU 900k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "TalonTake J.",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Kila Timu Ifunge (GG / BTTS)",
    analysisText:
      "Pambano kali kati ya Azam FC na Simba SC pale Chamazi Complex. Mashambulizi ya pande zote mbili yatakua makali na uwezekano wa kufungana ni mkubwa.",
  },
  {
    id: "tip-17",
    sport: "Football",
    category: "Tanzania",
    league: "Ligi Kuu Bara",
    gender: "Woman",
    time: "Kesho, 15:30 EAT",
    status: "UPCOMING",
    confidence: 87,
    homeTeam: {
      name: "Simba Queens",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Yanga Princess",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    odds: {
      home: 1.6,
      draw: 3.75,
      away: 4.8,
    },
    payoutBadge: "FBU 700k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Simba Queens Kushinda (FT)",
    analysisText:
      "Simba Queens wamekuwa wakitawala soka la wanawake nchini Tanzania. Wakiwa nyumbani, wana rekodi imara ya kutopoteza dhidi ya mahasimu wao Yanga Princess.",
  },
  {
    id: "tip-18",
    sport: "Football",
    category: "Burundi",
    league: "Primus League",
    gender: "Man",
    time: "Leo, 16:00 EAT",
    status: "LIVE",
    liveMinutes: "82'",
    confidence: 91,
    homeTeam: {
      name: "Vital'O FC",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    awayTeam: {
      name: "Bumamuru FC",
      bgGlow: "rgba(245, 158, 11, 0.3)",
    },
    odds: {
      home: 1.95,
      draw: 3.0,
      away: 3.6,
    },
    payoutBadge: "FBU 600k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Mtabiri Mkuu",
      avatarLetter: "M",
      isOfficial: false,
    },
    predictionTip: "Vital'O Kushinda au Sare (1X)",
    analysisText:
      "Vital'O wameonyesha fomu nzuri msimu huu na wanaongoza kwa pointi mfululizo uwanja wa nyumbani Bujumbura.",
  },
  {
    id: "tip-19",
    sport: "Football",
    category: "Burundi",
    league: "Primus League",
    gender: "Woman",
    time: "Leo, 14:00 EAT",
    status: "ENDED",
    confidence: 84,
    homeTeam: {
      name: "Fofila PF",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    awayTeam: {
      name: "PVP Buyenzi",
      bgGlow: "rgba(139, 92, 246, 0.3)",
    },
    odds: {
      home: 1.55,
      draw: 3.8,
      away: 5.0,
    },
    payoutBadge: "FBU 400k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LionessBets",
      avatarLetter: "L",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Fofila PF Kushinda (FT)",
    analysisText:
      "Ushindi thabiti kwa upande wa Fofila PF kutokana na mbinu imara za kiufundi tanzu mwanzo wa mchezo.",
  },
  {
    id: "tip-20",
    sport: "Football",
    category: "Rwanda",
    league: "Rwanda Premier League",
    gender: "Man",
    time: "Jumapili, 16:00 EAT",
    status: "UPCOMING",
    confidence: 89,
    homeTeam: {
      name: "APR FC",
      bgGlow: "rgba(255, 255, 255, 0.15)",
    },
    awayTeam: {
      name: "Rayon Sports",
      bgGlow: "rgba(37, 99, 235, 0.4)",
    },
    odds: {
      home: 2.1,
      draw: 3.2,
      away: 3.1,
    },
    payoutBadge: "FBU 850k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "TakeTalon Pro",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Magoli chini ya 2.5 (Under 2.5 Goals)",
    analysisText:
      "Pambano la dabi ya Kigali huwa kali sana kiasi kwamba ulinzi wa pande zote mbili unajipanga imara kuzuia makosa.",
  },
  {
    id: "tip-21",
    sport: "Football",
    category: "Rwanda",
    league: "Rwanda Premier League",
    gender: "Woman",
    time: "Jumapili, 14:00 EAT",
    status: "UPCOMING",
    confidence: 85,
    homeTeam: {
      name: "AS Kigali Women",
      bgGlow: "rgba(234, 179, 8, 0.3)",
    },
    awayTeam: {
      name: "Inyemera WFC",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    odds: {
      home: 1.4,
      draw: 4.0,
      away: 6.5,
    },
    payoutBadge: "FBU 300k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LionessBets",
      avatarLetter: "L",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "AS Kigali Women Kushinda (FT)",
    analysisText:
      "AS Kigali wameshinda mataji mengi ya ligi ya wanawake Rwanda na wana kikosi chenye uzoefu mkubwa kuliko Inyemera.",
  },
  {
    id: "tip-22",
    sport: "Football",
    category: "Kenya",
    league: "FKF Premier League",
    gender: "Man",
    time: "Kesho, 15:00 EAT",
    status: "UPCOMING",
    confidence: 86,
    homeTeam: {
      name: "Gor Mahia",
      bgGlow: "rgba(34, 197, 94, 0.4)",
    },
    awayTeam: {
      name: "AFC Leopards",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 1.85,
      draw: 3.2,
      away: 4.0,
    },
    payoutBadge: "FBU 750k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "BetMaster TZ",
      avatarLetter: "B",
      isOfficial: false,
    },
    predictionTip: "Gor Mahia Kushinda (FT)",
    analysisText:
      "Derby ya Mashemeji! Gor Mahia wameendelea kuwa timu bora zaidi nchini Kenya wakiwa na safu kali ya ulinzi inayozuia mashambulizi yote mepesi.",
  },
  {
    id: "tip-23",
    sport: "Football",
    category: "Kenya",
    league: "FKF Premier League",
    gender: "Woman",
    time: "Kesho, 13:00 EAT",
    status: "UPCOMING",
    confidence: 82,
    homeTeam: {
      name: "Vihiga Queens",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    awayTeam: {
      name: "Ulinzi Starlets",
      bgGlow: "rgba(220, 38, 38, 0.3)",
    },
    odds: {
      home: 1.7,
      draw: 3.4,
      away: 4.2,
    },
    payoutBadge: "FBU 500k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Magoli zaidi ya 1.5 (Over 1.5 Goals)",
    analysisText:
      "Vihiga Queens wana ushambuliaji hatari sana nyumbani kwao, wakati Ulinzi Starlets wakiwa hatari pia kwenye mashambulizi ya kushtukiza.",
  },
  {
    id: "tip-24",
    sport: "Football",
    category: "Ouganda",
    league: "Uganda Premier League",
    gender: "Man",
    time: "Kesho, 16:00 EAT",
    status: "UPCOMING",
    confidence: 88,
    homeTeam: {
      name: "Vipers SC",
      bgGlow: "rgba(220, 38, 38, 0.3)",
    },
    awayTeam: {
      name: "KCCA FC",
      bgGlow: "rgba(234, 179, 8, 0.3)",
    },
    odds: {
      home: 2.05,
      draw: 3.1,
      away: 3.35,
    },
    payoutBadge: "FBU 650k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "TalonTake J.",
      avatarLetter: "T",
      badge: "OFFICIAL",
      isOfficial: true,
    },
    predictionTip: "Vipers SC Kushinda au Sare (1X)",
    analysisText:
      "Vipers SC wakiwa St Mary's Stadium Kitende wamekuwa na ngome madhubuti isiyotikisika kirahisi na wanatazamiwa kupata alama tatu muhimu.",
  },
  {
    id: "tip-25",
    sport: "Football",
    category: "Ouganda",
    league: "Uganda Premier League",
    gender: "Woman",
    time: "Kesho, 14:00 EAT",
    status: "UPCOMING",
    confidence: 84,
    homeTeam: {
      name: "Kampala Queens",
      bgGlow: "rgba(239, 68, 68, 0.3)",
    },
    awayTeam: {
      name: "She Corporate",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 1.65,
      draw: 3.5,
      away: 4.5,
    },
    payoutBadge: "FBU 450k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LionessBets",
      avatarLetter: "L",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Kampala Queens Kushinda (FT)",
    analysisText:
      "Malkia wa Kampala wana kikosi chenye ubunifu mkubwa na wachezaji wengi wa timu ya taifa ya wanawake ya Uganda.",
  },
  {
    id: "tip-26",
    sport: "Football",
    category: "Arabia",
    league: "Saudi Pro League",
    gender: "Man",
    time: "Leo, 21:00 EAT",
    status: "LIVE",
    liveMinutes: "45'",
    confidence: 93,
    homeTeam: {
      name: "Al Hilal",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "Al Nassr",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    odds: {
      home: 1.9,
      draw: 3.8,
      away: 3.3,
    },
    payoutBadge: "FBU 1,500k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Elite Tips",
      avatarLetter: "E",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Al Hilal Kushinda au Sare (1X)",
    analysisText:
      "Al Hilal wana nidhamu ya kipekee ya mchezo na hawajapoteza mechi nyumbani dhidi ya Al Nassr ya Cristiano Ronaldo kwa misimu miwili iliyopita.",
  },
  {
    id: "tip-27",
    sport: "Football",
    category: "Allemagne",
    league: "Bundesliga",
    gender: "Woman",
    time: "Leo, 18:30 EAT",
    status: "ENDED",
    confidence: 90,
    homeTeam: {
      name: "Bayern Munich Women",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Wolfsburg Women",
      bgGlow: "rgba(34, 197, 94, 0.3)",
    },
    odds: {
      home: 1.85,
      draw: 3.5,
      away: 3.65,
    },
    payoutBadge: "FBU 1,000k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Bayern Munich Women Kushinda (FT)",
    analysisText:
      "Ushindi mkubwa kwa upande wa Bayern Munich wanawake dhidi ya washindani wao wakuu Wolfsburg nchini Ujerumani.",
  },
  {
    id: "tip-28",
    sport: "Football",
    category: "France",
    league: "Ligue 1",
    gender: "Woman",
    time: "Jumapili, 18:00 EAT",
    status: "UPCOMING",
    confidence: 91,
    homeTeam: {
      name: "Lyon Women",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    awayTeam: {
      name: "PSG Women",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    odds: {
      home: 1.55,
      draw: 3.9,
      away: 4.85,
    },
    payoutBadge: "FBU 1,100k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LionessBets",
      avatarLetter: "L",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Lyon Women Kushinda (FT)",
    analysisText:
      "Lyon ndio miamba ya soka ya wanawake barani Ulaya. Fomu yao ya nyumbani ni thabiti na inawabeba kuibuka washindi.",
  },
  {
    id: "tip-29",
    sport: "Football",
    category: "Italy",
    league: "Serie A",
    gender: "Woman",
    time: "Jumatano, 19:30 EAT",
    status: "UPCOMING",
    confidence: 85,
    homeTeam: {
      name: "Juventus Women",
      bgGlow: "rgba(255, 255, 255, 0.15)",
    },
    awayTeam: {
      name: "Roma Women",
      bgGlow: "rgba(220, 38, 38, 0.3)",
    },
    odds: {
      home: 2.1,
      draw: 3.3,
      away: 3.0,
    },
    payoutBadge: "FBU 600k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "DadaKipira",
      avatarLetter: "D",
      badge: "LADY",
      isOfficial: true,
    },
    predictionTip: "Magoli chini ya 2.5 (Under 2.5 Goals)",
    analysisText:
      "Kichwa cha dabi hii ya kipekee kitakuwa cha tahadhari. Ulinzi madhubuti kwa pande zote mbili utaleta mchezo wa mabao machache.",
  },
  {
    id: "game-tip-1",
    sport: "Games",
    category: "Aviator",
    league: "Aviator",
    gender: "Man",
    time: "Hivi Sasa (Live prediction)",
    status: "LIVE",
    liveMinutes: "Round 234",
    confidence: 96,
    homeTeam: {
      name: "Flight 1.50x",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Flight 3.00x+",
      bgGlow: "rgba(245, 158, 11, 0.4)",
    },
    odds: {
      home: 1.5,
      draw: 2.0,
      away: 3.5,
    },
    payoutBadge: "FBU 1,200k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "AviatorAI",
      avatarLetter: "A",
      badge: "BOT",
      isOfficial: true,
    },
    predictionTip: "Vuka Kiwango cha 2.10x",
    analysisText:
      "Mchanganuo wa algorithm unaonesha mzunguko huu una nafasi kubwa ya kufikia kizidisho cha juu cha zaidi ya x2.10 kabla ya ndege kupaa.",
  },
  {
    id: "game-tip-2",
    sport: "Games",
    category: "Multiplayer",
    league: "Ludo",
    gender: "Woman",
    time: "Leo, 21:00 EAT",
    status: "UPCOMING",
    confidence: 87,
    homeTeam: {
      name: "Ludo Stars East Africa",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    awayTeam: {
      name: "Dar Ludo Queens",
      bgGlow: "rgba(139, 92, 246, 0.3)",
    },
    odds: {
      home: 1.8,
      draw: 3.0,
      away: 1.95,
    },
    payoutBadge: "FBU 500k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "LudoChamp",
      avatarLetter: "L",
      badge: "STAR",
      isOfficial: false,
    },
    predictionTip: "Dar Ludo Queens Kushinda",
    analysisText:
      "Queens wana uzoefu wa hali ya juu wa kukata kete za wapinzani na wameshinda mechi tatu zilizopita kwa kete 4 zote kuingia nyumbani.",
  },
  {
    id: "game-tip-3",
    sport: "Games",
    category: "Multiplayer",
    league: "War 🔫",
    gender: "Man",
    time: "Kesho, 19:30 EAT",
    status: "UPCOMING",
    confidence: 90,
    homeTeam: {
      name: "Guerriers du Burundi",
      bgGlow: "rgba(239, 68, 68, 0.3)",
    },
    awayTeam: {
      name: "Tanzania Commando Clan",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 2.2,
      draw: 5.0,
      away: 1.55,
    },
    payoutBadge: "FBU 1,800k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "WarZone",
      avatarLetter: "W",
      badge: "VIP",
      isOfficial: true,
    },
    predictionTip: "Tanzania Commando Kushinda (First Blood + Victory)",
    analysisText:
      "Tanzania Commando wana mikakati kabambe ya mashambulizi ya kuvizia (stealth mode) na silaha nzito. Wana uwezekano wa 90% kuchukua ushindi.",
  },
  {
    id: "game-tip-4",
    sport: "Games",
    category: "Multiplayer",
    league: "Moto 🏍️",
    gender: "Man",
    time: "Jumatatu, 14:00 EAT",
    status: "UPCOMING",
    confidence: 82,
    homeTeam: {
      name: "Marc Marquez Virtual",
      bgGlow: "rgba(245, 158, 11, 0.3)",
    },
    awayTeam: {
      name: "Valentino Rossi Legacy",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    odds: {
      home: 1.65,
      draw: 12.0,
      away: 2.1,
    },
    payoutBadge: "FBU 900k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "MotoRider",
      avatarLetter: "M",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Marc Marquez Kushinda Lap ya Kwanza",
    analysisText:
      "Marquez ana sifa ya kuanza kwa kasi ya kimbunga kwenye kona za kwanza. Hii inampa nafasi kubwa ya kuongoza tangu mwanzo.",
  },
  {
    id: "game-tip-5",
    sport: "Games",
    category: "Multiplayer",
    league: "Race 🏎️",
    gender: "Woman",
    time: "Leo, 16:30 EAT",
    status: "LIVE",
    liveMinutes: "Lap 12/50",
    confidence: 89,
    homeTeam: {
      name: "Hamilton Super Sim",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    awayTeam: {
      name: "Verstappen Pro Bot",
      bgGlow: "rgba(234, 179, 8, 0.3)",
    },
    odds: {
      home: 1.85,
      draw: 15.0,
      away: 1.85,
    },
    payoutBadge: "FBU 2,000k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "F1Expert",
      avatarLetter: "F",
      badge: "VIP",
      isOfficial: false,
    },
    predictionTip: "Verstappen Pro Bot Kupata Lap ya Kasi Zaidi (Fastest Lap)",
    analysisText:
      "Gari la Verstappen lina vifaa vya 'soft tyres' vipya kwa raundi hii na anatarajiwa kuvunja rekodi ya kasi ya mzunguko hivi sasa.",
  },
  {
    id: "game-tip-6",
    sport: "Games",
    category: "Football",
    league: "FIFA Super Cup",
    gender: "Man",
    time: "Kesho, 12:00 EAT",
    status: "UPCOMING",
    confidence: 91,
    homeTeam: {
      name: "Paris Saint-Germain Esports",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    awayTeam: {
      name: "Manchester City Esports",
      bgGlow: "rgba(56, 189, 248, 0.4)",
    },
    odds: {
      home: 2.1,
      draw: 3.6,
      away: 2.3,
    },
    payoutBadge: "FBU 1,400k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "EsportTz",
      avatarLetter: "E",
      badge: "PRO",
      isOfficial: true,
    },
    predictionTip: "Mabao Zaidi ya 3.5 (Over 3.5)",
    analysisText:
      "Wachezaji hawa wawili wanajulikana kwa staili yao ya kushambulia bila kuzuia (ultra-offensive). Magoli yatakuwa mengi sana mchezo huu.",
  },
  {
    id: "game-tip-7",
    sport: "Games",
    category: "Basketball",
    league: "NBA 2K Championship",
    gender: "Woman",
    time: "Kesho, 15:30 EAT",
    status: "UPCOMING",
    confidence: 84,
    homeTeam: {
      name: "LA Lakers Esports",
      bgGlow: "rgba(245, 158, 11, 0.3)",
    },
    awayTeam: {
      name: "Boston Celtics Esports",
      bgGlow: "rgba(16, 185, 129, 0.3)",
    },
    odds: {
      home: 1.75,
      draw: 10.0,
      away: 2.1,
    },
    payoutBadge: "FBU 800k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "VirtualDunk",
      avatarLetter: "V",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "LA Lakers Esports Kushinda",
    analysisText:
      "Lakers wanashikiliwa na mchezaji namba moja duniani wa virtual NBA 2K ambaye ana rekodi ya kushinda michezo 15 mfululizo.",
  },
  {
    id: "game-tip-8",
    sport: "Games",
    category: "Boxing",
    league: "Fight Night Virtual",
    gender: "Man",
    time: "Leo, 22:00 EAT",
    status: "UPCOMING",
    confidence: 88,
    homeTeam: {
      name: "Mike Tyson Classic",
      bgGlow: "rgba(220, 38, 38, 0.3)",
    },
    awayTeam: {
      name: "Muhammad Ali Classic",
      bgGlow: "rgba(59, 130, 246, 0.3)",
    },
    odds: {
      home: 1.9,
      draw: 12.0,
      away: 1.9,
    },
    payoutBadge: "FBU 1,500k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "ConsoleKO",
      avatarLetter: "C",
      badge: "VIP",
      isOfficial: true,
    },
    predictionTip: "Mike Tyson Kupata Ushindi kwa Knockout (KO)",
    analysisText:
      "Nguvu ya kwanza ya Mike Tyson kwenye simu hii ya 'Fight Night' ni kubwa mno na mara nyingi humaliza pambano raundi tatu za kwanza.",
  },
];

export const TOP_TIPSTERS: Tipster[] = [];
