import { MatchTip } from "./types";

export const INITIAL_UNLOCKERS_TIPS: MatchTip[] = [
  {
    id: "unlocker-1",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Leo, 16:00 CAT",
    status: "UPCOMING",
    confidence: 85,
    homeTeam: {
      name: "Vital'O FC",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    awayTeam: {
      name: "Bumamuru FC",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    odds: {
      home: 10.5,
      draw: 5.0,
      away: 30.0,
    },
    payoutBadge: "FBU 2,500k+",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Amissi",
      avatarLetter: "A",
      badge: "ELITE",
      isOfficial: false,
    },
    predictionTip: "Vital'O FC Kushinda (Odds: 10.50) au Sare",
    analysisText:
      "Pambano la kukata na shoka. Bumamuru wako vizuri lakini Vital'O wana nguvu ya mashabiki wa nyumbani Bujumbura. Odds ni kubwa sana kwa sababu timu zote zimeimarisha safu ya ushambuliaji.",
  },
  {
    id: "unlocker-2",
    sport: "Football",
    category: "USA",
    league: "MLS",
    gender: "Man",
    time: "Leo, 22:30 CAT",
    status: "UPCOMING",
    confidence: 88,
    homeTeam: {
      name: "Inter Miami",
      bgGlow: "rgba(244, 114, 182, 0.4)",
    },
    awayTeam: {
      name: "LA Galaxy",
      bgGlow: "rgba(14, 165, 233, 0.4)",
    },
    odds: {
      home: 15.0,
      draw: 6.5,
      away: 35.0,
    },
    payoutBadge: "FBU 1,800k+",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Messi",
      avatarLetter: "M",
      badge: "GOLD",
      isOfficial: false,
    },
    predictionTip: "Inter Miami Kushinda Mechi Nzima",
    analysisText:
      "Messi ana fomu ya ajabu sana wiki hii. Hii odds ya 15.00 ni fursa isiyo ya kawaida na isiyopaswa kupitwa kabisa.",
  },
  {
    id: "unlocker-3",
    sport: "Football",
    category: "UK",
    league: "Premier League",
    gender: "Man",
    time: "Kesho, 18:30 CAT",
    status: "UPCOMING",
    confidence: 79,
    homeTeam: {
      name: "Chelsea",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "Man United",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    odds: {
      home: 12.0,
      draw: 7.0,
      away: 25.0,
    },
    payoutBadge: "FBU 1,200k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Elon Musk",
      avatarLetter: "E",
      badge: "TESLA",
      isOfficial: false,
    },
    predictionTip: "Chelsea Kupata Ushindi Mwembamba",
    analysisText:
      "Mabadiliko ya mfumo wa timu zote mbili yataleta mchezo wenye msisimko na magoli mengi lakini Chelsea wataibuka kidedea Stamford Bridge.",
  },
  {
    id: "unlocker-4",
    sport: "Football",
    category: "France",
    league: "Ligue 1",
    gender: "Man",
    time: "Kesho, 21:00 CAT",
    status: "UPCOMING",
    confidence: 82,
    homeTeam: {
      name: "PSG",
      bgGlow: "rgba(30, 41, 59, 0.4)",
    },
    awayTeam: {
      name: "Marseille",
      bgGlow: "rgba(14, 165, 233, 0.4)",
    },
    odds: {
      home: 9.5,
      draw: 5.2,
      away: 28.5,
    },
    payoutBadge: "FBU 900k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Mark Zucker",
      avatarLetter: "M",
      badge: "META",
      isOfficial: false,
    },
    predictionTip: "Marseille Kupata Sare au Ushindi",
    analysisText:
      "Marseille wamejiandaa vizuri na wana mbinu imara za kujihami kukabiliana na safu ya mashambulizi ya PSG kule Paris.",
  },
  {
    id: "unlocker-5",
    sport: "Football",
    category: "Saudi",
    league: "Saudi Pro League",
    gender: "Man",
    time: "Kesho, 20:00 CAT",
    status: "UPCOMING",
    confidence: 91,
    homeTeam: {
      name: "Al Nassr",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    awayTeam: {
      name: "Al Hilal",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    odds: {
      home: 18.0,
      draw: 8.0,
      away: 45.0,
    },
    payoutBadge: "FBU 3,000k+",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Cristiano Ronaldo",
      avatarLetter: "C",
      badge: "CR7",
      isOfficial: false,
    },
    predictionTip: "Al Nassr Kushinda Nyumbani",
    analysisText:
      "Morali ya timu iko juu sana na uwanja wa nyumbani utawapa nguvu ya kipekee kuandika historia dhidi ya mahasimu wao.",
  },
  {
    id: "unlocker-6",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 2 Zijazo, 15:00 CAT",
    status: "UPCOMING",
    confidence: 84,
    homeTeam: {
      name: "Flambeau du Centre",
      bgGlow: "rgba(249, 115, 22, 0.4)",
    },
    awayTeam: {
      name: "Aigle Noir",
      bgGlow: "rgba(30, 41, 59, 0.4)",
    },
    odds: {
      home: 11.0,
      draw: 5.5,
      away: 32.0,
    },
    payoutBadge: "FBU 1,500k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Saido Ntibazonkiza",
      avatarLetter: "S",
      badge: "LEGEND",
      isOfficial: false,
    },
    predictionTip: "Flambeau du Centre Kushinda au Sare",
    analysisText:
      "Mchezo mgumu wa dabi ya Gitega. Flambeau wamekuwa imara sana nyumbani na wana uzoefu wa kutosha.",
  },
  {
    id: "unlocker-7",
    sport: "Football",
    category: "Tanzania",
    league: "Ligi Kuu Bara",
    gender: "Man",
    time: "Siku 2 Zijazo, 19:00 CAT",
    status: "UPCOMING",
    confidence: 87,
    homeTeam: {
      name: "Simba SC",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Yanga SC",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    odds: {
      home: 14.0,
      draw: 6.0,
      away: 29.0,
    },
    payoutBadge: "FBU 2,200k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Bigirimana",
      avatarLetter: "B",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "Simba SC Kupata Ushindi Nyumbani",
    analysisText:
      "Dabi maarufu ya Kariakoo yenye msisimko mkubwa. Simba SC wana nafasi nzuri ya kulipiza kisasi kwa kutumia uwanja wa nyumbani vizuri.",
  },
  {
    id: "unlocker-8",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 3 Zijazo, 14:30 CAT",
    status: "UPCOMING",
    confidence: 80,
    homeTeam: {
      name: "Messager Ngozi",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    awayTeam: {
      name: "Olympic Star",
      bgGlow: "rgba(14, 165, 233, 0.4)",
    },
    odds: {
      home: 10.0,
      draw: 5.0,
      away: 30.0,
    },
    payoutBadge: "FBU 1,000k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Shabani",
      avatarLetter: "S",
      badge: "EXPERT",
      isOfficial: false,
    },
    predictionTip: "Olympic Star Kushinda",
    analysisText:
      "Olympic Star wameonesha mabadiliko makubwa katika michezo yao miwili ya hivi karibuni ugenini.",
  },
  {
    id: "unlocker-9",
    sport: "Football",
    category: "Africa",
    league: "CAF Champions League",
    gender: "Man",
    time: "Siku 3 Zijazo, 21:00 CAT",
    status: "UPCOMING",
    confidence: 83,
    homeTeam: {
      name: "Petro Luanda",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    awayTeam: {
      name: "Esperance Tunis",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    odds: {
      home: 16.5,
      draw: 7.5,
      away: 40.0,
    },
    payoutBadge: "FBU 1,600k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Nduwarugira",
      avatarLetter: "N",
      badge: "VIP",
      isOfficial: false,
    },
    predictionTip: "Petro Luanda Kushinda au Sare",
    analysisText:
      "Esperance ni timu yenye uzoefu lakini Petro Luanda wamefanya uwekezaji mkubwa sana msimu huu kuelekea nusu fainali.",
  },
  {
    id: "unlocker-10",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 4 Zijazo, 16:00 CAT",
    status: "UPCOMING",
    confidence: 86,
    homeTeam: {
      name: "Rukinzo FC",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    awayTeam: {
      name: "Musongati FC",
      bgGlow: "rgba(16, 185, 129, 0.4)",
    },
    odds: {
      home: 13.0,
      draw: 5.8,
      away: 31.0,
    },
    payoutBadge: "FBU 1,100k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Berahino",
      avatarLetter: "B",
      badge: "ELITE",
      isOfficial: false,
    },
    predictionTip: "Rukinzo FC Kushinda Nyumbani",
    analysisText:
      "Rukinzo FC wana safu imara ya ulinzi ambayo itawazuia Musongati wasilete madhara kwenye lango lao.",
  },
  {
    id: "unlocker-11",
    sport: "Football",
    category: "Tanzania",
    league: "Ligi Kuu Bara",
    gender: "Man",
    time: "Siku 4 Zijazo, 17:00 CAT",
    status: "UPCOMING",
    confidence: 81,
    homeTeam: {
      name: "Azam FC",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "KMC FC",
      bgGlow: "rgba(30, 41, 59, 0.4)",
    },
    odds: {
      home: 12.5,
      draw: 6.2,
      away: 27.5,
    },
    payoutBadge: "FBU 1,400k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Fiston Abdul Razak",
      avatarLetter: "F",
      badge: "LEGEND",
      isOfficial: false,
    },
    predictionTip: "Azam FC Kushinda Mechi Nzima",
    analysisText:
      "Azam FC wanahitaji pointi hizi tatu ili kujiweka nafasi nzuri ya uwakilishi wa kimataifa.",
  },
  {
    id: "unlocker-12",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 5 Zijazo, 15:30 CAT",
    status: "UPCOMING",
    confidence: 89,
    homeTeam: {
      name: "Inter Star",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Kayanza United",
      bgGlow: "rgba(16, 185, 129, 0.4)",
    },
    odds: {
      home: 15.5,
      draw: 6.8,
      away: 33.0,
    },
    payoutBadge: "FBU 1,750k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Ndikumana",
      avatarLetter: "N",
      badge: "EXPERT",
      isOfficial: false,
    },
    predictionTip: "Inter Star Kupata Sare au Ushindi",
    analysisText:
      "Mechi ya dabi ya jiji yenye ushindani mkali. Kayanza wanasafiri wakiwa na presha ya kushuka daraja.",
  },
  {
    id: "unlocker-13",
    sport: "Football",
    category: "UK",
    league: "Premier League",
    gender: "Man",
    time: "Siku 5 Zijazo, 15:00 CAT",
    status: "UPCOMING",
    confidence: 77,
    homeTeam: {
      name: "Arsenal",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    awayTeam: {
      name: "Tottenham",
      bgGlow: "rgba(255, 255, 255, 0.15)",
    },
    odds: {
      home: 10.0,
      draw: 5.5,
      away: 30.0,
    },
    payoutBadge: "FBU 1,300k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Jeff Bezos",
      avatarLetter: "J",
      badge: "AMZN",
      isOfficial: false,
    },
    predictionTip: "Arsenal Kushinda au Sare",
    analysisText:
      "North London dabi huwa haitabiriki kirahisi lakini Emirates daima ni ngome imara ya washika bunduki.",
  },
  {
    id: "unlocker-14",
    sport: "Football",
    category: "Saudi",
    league: "Saudi Pro League",
    gender: "Man",
    time: "Siku 6 Zijazo, 20:30 CAT",
    status: "UPCOMING",
    confidence: 82,
    homeTeam: {
      name: "Al Hilal",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    awayTeam: {
      name: "Al Ittihad",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    odds: {
      home: 13.5,
      draw: 6.0,
      away: 29.5,
    },
    payoutBadge: "FBU 1,450k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Neymar Jr",
      avatarLetter: "N",
      badge: "SANTOS",
      isOfficial: false,
    },
    predictionTip: "Al Hilal Kushinda Mechi Nzima",
    analysisText:
      "Al Hilal wana fomu bora na wameshinda mechi tano za mwisho nyumbani bila kuruhusu goli.",
  },
  {
    id: "unlocker-15",
    sport: "Football",
    category: "Espagne",
    league: "LaLiga",
    gender: "Man",
    time: "Siku 6 Zijazo, 21:00 CAT",
    status: "UPCOMING",
    confidence: 90,
    homeTeam: {
      name: "Real Madrid",
      bgGlow: "rgba(59, 130, 246, 0.4)",
    },
    awayTeam: {
      name: "Atletico Madrid",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    odds: {
      home: 17.0,
      draw: 7.5,
      away: 38.0,
    },
    payoutBadge: "FBU 2,800k+",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Mbappé",
      avatarLetter: "M",
      badge: "GOLDEN",
      isOfficial: false,
    },
    predictionTip: "Real Madrid Kushinda Magoli Zaidi ya 2.5",
    analysisText:
      "El Derbi madrileño. Real Madrid wapo vizuri Bernabeu na wana washambuliaji wenye kasi kubwa sana.",
  },
  {
    id: "unlocker-16",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 7 Zijazo, 15:00 CAT",
    status: "UPCOMING",
    confidence: 83,
    homeTeam: {
      name: "Dynamik FC",
      bgGlow: "rgba(239, 68, 68, 0.4)",
    },
    awayTeam: {
      name: "Le Messager",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    odds: {
      home: 11.5,
      draw: 5.3,
      away: 31.5,
    },
    payoutBadge: "FBU 1,250k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Amissi Cedric",
      avatarLetter: "A",
      badge: "VIP",
      isOfficial: false,
    },
    predictionTip: "Sare Mechi Hii",
    analysisText:
      "Mechi ya mbinu kali. Timu zote mbili zitacheza kwa kujihami kwanza kuepuka kufungwa.",
  },
  {
    id: "unlocker-17",
    sport: "Football",
    category: "UK",
    league: "Premier League",
    gender: "Man",
    time: "Siku 7 Zijazo, 17:30 CAT",
    status: "UPCOMING",
    confidence: 86,
    homeTeam: {
      name: "Liverpool",
      bgGlow: "rgba(220, 38, 38, 0.4)",
    },
    awayTeam: {
      name: "Everton",
      bgGlow: "rgba(30, 58, 138, 0.4)",
    },
    odds: {
      home: 12.0,
      draw: 5.5,
      away: 30.0,
    },
    payoutBadge: "FBU 1,900k",
    isPremium: false,
    isLocked: false,
    tipster: {
      name: "Steve Jobs",
      avatarLetter: "S",
      badge: "APPLE",
      isOfficial: false,
    },
    predictionTip: "Liverpool Kupata Ushindi Mkubwa",
    analysisText:
      "Dabi ya Merseyside. Liverpool nyumbani Anfield daima wana nguvu ya kutawala mchezo huu.",
  },
  {
    id: "unlocker-18",
    sport: "Football",
    category: "Burundi",
    league: "Burundi Ligue A",
    gender: "Man",
    time: "Siku 8 Zijazo, 14:00 CAT",
    status: "UPCOMING",
    confidence: 85,
    homeTeam: {
      name: "Telaviv FC",
      bgGlow: "rgba(14, 165, 233, 0.4)",
    },
    awayTeam: {
      name: "LLB Amasipiri",
      bgGlow: "rgba(234, 179, 8, 0.4)",
    },
    odds: {
      home: 14.5,
      draw: 6.0,
      away: 34.0,
    },
    payoutBadge: "FBU 1,350k",
    isPremium: true,
    isLocked: true,
    tipster: {
      name: "Kanazimwe",
      avatarLetter: "K",
      badge: "PRO",
      isOfficial: false,
    },
    predictionTip: "LLB Amasipiri Kushinda",
    analysisText:
      "LLB Amasipiri wamerejesha viwango vyao baada ya kusajili viungo wapya wa kiushindani mwezi huu.",
  },
];
